# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run Table Bookings unit tests...🚀

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    services:
      postgres:
        image: postgres:latest
        env: 
          POSTGRES_USER: coder
          POSTGRES_PASSWORD: coder123
          POSTGRES_DB: bookings
        ports:
        - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
        
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: npm install
    - name: create postgresql tables
      run: PGPASSWORD=coder123 psql -h localhost -U coder -d bookings -a -f ./sql/table.sql
    - name: populate postgresql tables
      run: PGPASSWORD=coder123 psql -h localhost -U coder -d bookings -a -f ./sql/data.sql
    - name: run tests with postgresql
      run:
        npm test
      env:
        DATABASE_URL: postgres://coder:coder123@localhost:5432/bookings
